spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:prices
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      platform: h2
      mode: always
      data-locations: classpath:sql/initial_data.sql